before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.monach.us

build:
  stage: build
  script:
    - docker build --pull -t registry.monach.us/docker/zcash --build-arg VCS_REF=$CI_BUILD_REF .
    - docker push registry.monach.us/docker/zcash

push_to_docker_hub:
  stage: deploy
  script:
    - docker login -u $HUB_USERNAME -p $HUB_PASSWORD
    - docker tag registry.monach.us/docker/zcash:latest monachus/zcash:latest
    - docker push monachus/zcash

# ping_microbadger:
#   stage: deploy
#   script:
#     - curl -XPOST https://hooks.microbadger.com/images/monachus/zcash/4POfPA2VlfMloTzUFD50AF1fiMY=

